project_name: dbh

builds:
  - main: ./cmd/dbh
    binary: dbh
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: dbh
    repository:
      owner: genesisdayrit
      name: tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/genesisdayrit/dbharness
    description: DB Harness project initializer
    install: |
      bin.install "dbh"
    test: |
      system "#{bin}/dbh", "init", "--help"
